### ISSUE TITLE
Consider submitting to the asset library

### ISSUE THREAD

**Issue by aaronfranke** [OBKF/Godot-Trail-System#1]
This asset looks really cool. It would be good for visibility if you submitted it to the asset library.

https://godotengine.org/asset-library/asset

https://docs.godotengine.org/en/latest/tutorials/assetlib/uploading_to_assetlib.html

**Comment by OBKF** [comment]
@aaronfranke I totally forgot to do that, I am submitting now.
Thank you for the suggestion.
