### ISSUE TITLE
Adding this plugin to Awesome Godot repo.

### ISSUE THREAD

**Issue by jegor377** [OBKF/Godot-Trail-System#3]
Your work is awesome! Do you plan on adding it to the [Awesome Godot](https://github.com/godotengine/awesome-godot) repository? It may be really helpful for other Godot users. :)

**Comment by OBKF** [comment]
Hi @jegor377 . 
Thanks, I hope it was helpful, the plugin is already in the official store, feel free to add it there since I am a bit busy and I don't have time to fix some issues in it (hopefully I can get some free time by the end of the year :p .
If it has to be me tell me and i will do it.

**Comment by jegor377** [comment]
Okay, I [PR](https://github.com/godotengine/awesome-godot/pull/143) the repo. :D

**Comment by jegor377** [comment]
Your repo is now in Awesome Godot so you can close this issue. :)

**Comment by jegor377** [comment]
Your repo is now in Awesome Godot so I close this issue. :D
